- name: set HADOOP_HOME to /root/.bashrc
  lineinfile:
    path: /root/.bashrc
    line: "export HADOOP_HOME={{ hadoop_install_folder }}/hadoop-{{ hadoop_version }}"

- name: set PATH
  lineinfile:
    path: /root/.bashrc
    line: "export PATH=$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$PATH"
